#!/usr/bin/python3
"""class definition of a city"""
from sqlalchemy import Column, String, Integer
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()


class City(Base):
    """declarative class definition for city"""
    id = Column(Integer, nullable=False, autogenerated=True, primary_key=True)
    name = Column(String(128), nullable=False)
    state_id = Column(Integer, nullable=False, ForeignKey("State.id"))
